import { FC, ReactNode } from 'react'
import '@/styles/global.sass'

export const metadata = {
  title: 'Todo App',
  description: 'Generated by create next app',
}

interface IRootLayout {
  children: ReactNode
}

const RootLayout: FC<IRootLayout> = ({ children }) => {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  )
}

export default RootLayout
